[program:egoqc-postgres]
command=/usr/bin/pg_ctlcluster --foreground 14 main start
priority=10
autostart=true
autorestart=true
startsecs=3
stopsignal=INT
stopasgroup=true
killasgroup=true
stdout_logfile=/srv/egoqc/results/egoqc-postgres.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=3
redirect_stderr=true
