from __future__ import annotations


# Self-contained by design: evidence review must work on an offline development box.
WORKBENCH_TEMPLATE = r'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>EgoQC 人工复检</title>
<style>
:root{color-scheme:light;--canvas:#e9ebed;--panel:#f7f7f5;--paper:#fff;--ink:#202326;--muted:#676d72;--quiet:#8d9296;--line:#c9cdd0;--line-strong:#92989d;--accent:#bf4a27;--accent-soft:#f5e4de;--danger:#a52d27;--warn:#8a5d18;--ok:#2d684f;--media:#16191b;--media-line:#34393d;--focus:#2266c7;--r:2px;--mono:"SFMono-Regular",Consolas,"Liberation Mono",monospace;--sans:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif}
@media(prefers-color-scheme:dark){:root{color-scheme:dark;--canvas:#151719;--panel:#1d2022;--paper:#242729;--ink:#f0f1ef;--muted:#b1b5b7;--quiet:#858b8f;--line:#3e4347;--line-strong:#676d72;--accent:#e27652;--accent-soft:#482a22;--danger:#ee847c;--warn:#e3b66a;--ok:#79ba98;--media:#0e1011;--media-line:#34393d;--focus:#75a7ee}}
*{box-sizing:border-box}[hidden]{display:none!important}html,body{height:100%}body{margin:0;background:var(--canvas);color:var(--ink);font:13px/1.45 var(--sans);overflow:hidden}button,input,textarea,select{font:inherit;color:inherit;border:1px solid var(--line-strong);border-radius:var(--r);background:var(--paper)}button{cursor:pointer;min-height:30px;padding:5px 10px;font-weight:600}button:hover{border-color:var(--ink)}button:active{transform:translateY(1px)}button:disabled{cursor:not-allowed;opacity:.42}button:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible{outline:2px solid var(--focus);outline-offset:1px}.mono{font-family:var(--mono);font-variant-numeric:tabular-nums}.muted{color:var(--muted)}.primary{background:var(--accent);border-color:var(--accent);color:#fff}.primary:hover{border-color:var(--ink)}
.app{height:100dvh;display:grid;grid-template-rows:52px 1fr}.command{display:grid;grid-template-columns:250px minmax(220px,1fr) auto;align-items:center;border-bottom:1px solid var(--line-strong);background:var(--panel)}.identity{height:100%;padding:8px 14px;border-right:1px solid var(--line);display:flex;align-items:baseline;gap:8px}.identity strong{font-size:15px;letter-spacing:-.02em}.identity span{font-size:11px;color:var(--muted)}.dataset{min-width:0;padding:0 14px;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.command-actions{height:100%;display:flex;align-items:center;gap:7px;padding:0 10px;border-left:1px solid var(--line)}.run-state,.count{font-family:var(--mono);font-size:11px;white-space:nowrap}.run-state{color:var(--muted);padding-right:8px}.count{padding:0 8px}
.workspace{min-height:0;display:grid;grid-template-columns:250px minmax(520px,1fr) 360px}.queue{min-height:0;display:grid;grid-template-rows:auto 1fr;background:var(--panel);border-right:1px solid var(--line-strong)}.queue-tools{padding:10px;border-bottom:1px solid var(--line)}.query-row{display:grid;grid-template-columns:1fr 88px;gap:6px}.query-row input,.query-row select{width:100%;height:31px;padding:5px 8px}.filters{display:flex;flex-wrap:wrap;margin-top:8px;border:1px solid var(--line)}.filters button{flex:1;min-height:27px;padding:3px 6px;border:0;border-right:1px solid var(--line);border-radius:0;background:transparent;font-size:11px}.filters button:last-child{border-right:0}.filters button.active{background:var(--ink);color:var(--panel)}.queue-list{overflow:auto}.queue-item{width:100%;border:0;border-bottom:1px solid var(--line);border-radius:0;background:transparent;text-align:left;padding:9px 11px;display:grid;grid-template-columns:1fr auto;gap:2px 8px}.queue-item:hover{background:var(--paper)}.queue-item.active{background:var(--accent-soft);box-shadow:inset 3px 0 var(--accent)}.queue-item b{font:600 12px var(--mono)}.queue-item small{grid-column:1/-1;color:var(--muted);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.status{font:700 10px var(--mono);letter-spacing:.03em}.status.rework,.status.reject{color:var(--danger)}.status.review,.status.unscored{color:var(--warn)}.status.accept{color:var(--ok)}.empty-page{padding:28px 14px;color:var(--muted)}
.stage{min-width:0;min-height:0;display:grid;grid-template-rows:41px minmax(0,1fr) auto 37px;background:var(--media);color:#e7e8e6}.media-bar{display:flex;align-items:center;gap:0;border-bottom:1px solid var(--media-line);background:#202427;padding:0 9px}.media-bar button{border:0;border-radius:0;background:transparent;color:#aeb3b6;min-height:40px;padding:0 11px;font-size:12px}.media-bar button.active{color:#fff;box-shadow:inset 0 -2px var(--accent)}.media-bar .frame-nav{margin-left:auto;display:flex;align-items:center;gap:5px}.media-bar .frame-nav button{border:1px solid #50565a;min-height:26px;height:26px;padding:0 8px}.media-bar .frame-nav span{font:11px var(--mono);color:#aeb3b6;min-width:76px;text-align:center}.media{min-height:0;position:relative;display:grid;place-items:center;overflow:auto;padding:12px}.media img,.media video{display:block;max-width:100%;max-height:100%;object-fit:contain}.media video{width:100%;height:100%;background:var(--media)}.media-empty{color:#adb2b5;padding:28px}.frame-rail{display:flex;gap:6px;min-height:0;overflow-x:auto;padding:8px 10px;border-top:1px solid var(--media-line);background:#1c1f21}.frame-thumb{position:relative;flex:0 0 92px;border:1px solid #494e52;border-radius:0;background:#111;padding:0;color:#ddd;text-align:left}.frame-thumb img{display:block;width:90px;height:51px;object-fit:cover}.frame-thumb span{display:block;padding:3px 5px;font:10px var(--mono)}.frame-thumb.active{border-color:var(--accent);box-shadow:0 0 0 1px var(--accent)}.frame-thumb.anomaly span{color:#ffb19a}.media-footer{height:37px;min-width:0;display:grid;grid-template-columns:auto minmax(0,1fr);gap:12px;align-items:center;padding:0 12px;background:#202427;border-top:1px solid var(--media-line);color:#aeb3b6;font-size:11px}.media-footer code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.inspector{min-height:0;overflow:auto;background:var(--panel);border-left:1px solid var(--line-strong)}.section{padding:12px 14px;border-bottom:1px solid var(--line)}.section-head{display:flex;justify-content:space-between;align-items:baseline;margin-bottom:8px}.section h2{font-size:12px;margin:0}.section-head span{font:10px var(--mono);color:var(--muted)}.gate{border-left:3px solid var(--line-strong);padding-left:9px}.gate.rework,.gate.reject{border-left-color:var(--danger)}.gate.accept{border-left-color:var(--ok)}.gate strong{font-size:14px}.gate p{margin:3px 0 0;color:var(--muted);font-size:11px}.issue-list{display:grid;gap:10px}.issue{display:grid;grid-template-columns:1fr auto;gap:3px 8px}.issue b{font-size:12px}.issue p{grid-column:1/-1;margin:0;color:var(--muted);font-size:11px}.issue-actions{display:flex;gap:3px;grid-column:1/-1}.issue-actions button{min-height:23px;padding:2px 6px;font-size:10px;border-color:var(--line)}.issue-actions button.selected{background:var(--ink);color:var(--panel)}.metrics{display:grid;grid-template-columns:1fr auto;gap:5px 12px;font-size:11px}.metrics span:nth-child(2n){font-family:var(--mono);text-align:right}.empty{color:var(--muted);font-size:11px}.reviewer{width:100%;height:31px;padding:5px 8px}.decisions{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:8px}.decision{font-size:11px}.decision.selected{background:var(--ink);color:var(--panel);border-color:var(--ink)}.defects{display:grid;grid-template-columns:1fr 1fr;gap:5px 10px;margin-top:10px}.defects label{display:flex;align-items:center;gap:6px;font-size:11px}.note{width:100%;min-height:76px;resize:vertical;padding:7px 8px;margin-top:10px}.review-state{margin-top:7px;font-size:11px;font-weight:700;color:var(--accent)}.policy{margin:8px 0 0;color:var(--muted);font-size:10px}.history{display:grid;gap:6px}.history-row{display:grid;grid-template-columns:auto 1fr;gap:8px;font-size:10px}.history-row time{font-family:var(--mono);color:var(--muted)}
.shortcut-dialog{width:min(580px,calc(100vw - 30px));border:1px solid var(--line-strong);border-radius:var(--r);background:var(--paper);color:var(--ink);padding:0}.shortcut-dialog::backdrop{background:rgba(12,14,15,.58)}.shortcut-dialog header{padding:13px 16px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}.shortcut-dialog h2{margin:0;font-size:14px}.shortcut-dialog .keys{padding:14px 16px;display:grid;grid-template-columns:repeat(2,1fr);gap:9px 22px}.key{display:grid;grid-template-columns:80px 1fr;gap:8px}.key kbd{font:11px var(--mono);color:var(--accent)}
@media(max-width:1180px){body{overflow:auto}.app{height:auto;min-height:100dvh}.workspace{grid-template-columns:230px minmax(460px,1fr)}.inspector{grid-column:1/-1;border-left:0;border-top:1px solid var(--line-strong);display:grid;grid-template-columns:repeat(3,1fr)}.section{border-right:1px solid var(--line)}}
@media(max-width:760px){.command{grid-template-columns:1fr auto}.identity{border-right:0}.dataset{display:none}.command-actions .run-state,.command-actions .count,.command-actions #import{display:none}.workspace{display:block}.queue{max-height:240px;border-right:0;border-bottom:1px solid var(--line-strong)}.stage{height:70dvh;grid-template-rows:41px minmax(0,1fr) auto 37px}.inspector{display:block}.section{border-right:0}.media-bar button{padding:0 7px}.frame-nav{display:none!important}.shortcut-dialog .keys{grid-template-columns:1fr}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
</style></head><body><div class="app">
<header class="command"><div class="identity"><strong>EgoQC</strong><span>交付复检台</span></div><div class="dataset">__DATASET_LABEL__</div><div class="command-actions"><span class="run-state" id="live-status">离线数据</span><span class="count" id="progress"></span><button id="shortcuts" title="键盘快捷键">快捷键</button><button id="import">导入</button><input id="file" type="file" accept=".jsonl" hidden><button id="export" class="primary">导出复检结果</button></div></header>
<main class="workspace"><aside class="queue"><div class="queue-tools"><div class="query-row"><input id="search" type="search" placeholder="搜索 episode、路径或问题" aria-label="搜索审核任务"><select id="sort" aria-label="队列排序"><option value="risk">风险优先</option><option value="episode">Episode</option><option value="pending">未审核优先</option></select></div><div class="filters"><button data-filter="all" class="active">全部</button><button data-filter="pending">待审</button><button data-filter="rework">返工</button><button data-filter="escalated">仲裁</button><button data-filter="reviewed">已审</button></div></div><div class="queue-list" id="queue"></div></aside>
<section class="stage"><div class="media-bar"><button data-media="sheet" class="active">总览</button><button data-media="frame">原始帧</button><button data-media="overlay">MANO 拟合</button><button data-media="source">原始视频</button><button data-media="annotated" id="annotated-tab">标注视频</button><div class="frame-nav"><button id="prev-frame" aria-label="上一抽样帧">[</button><span id="frame-position">0 / 0</span><button id="next-frame" aria-label="下一抽样帧">]</button></div></div><div class="media"><img id="image" alt="当前 episode 证据"><video id="video" controls preload="metadata" hidden></video><div id="media-empty" class="media-empty" hidden>证据尚未生成</div></div><div class="frame-rail" id="frame-rail"></div><div class="media-footer"><span id="frame-range"></span><code id="source-path"></code></div></section>
<aside class="inspector"><section class="section"><div class="section-head"><h2>系统门禁</h2><span id="provisional"></span></div><div class="gate" id="gate"><strong id="system-decision"></strong><p id="gate-copy"></p></div></section><section class="section"><div class="section-head"><h2>失败原因</h2><span>逐项复核</span></div><div class="issue-list" id="issues"></div></section><section class="section"><div class="section-head"><h2>关键指标</h2><span>原始数据</span></div><div class="metrics" id="metrics"></div></section><section class="section"><div class="section-head"><h2>人工结论</h2><span id="review-state"></span></div><input class="reviewer" id="reviewer" placeholder="审核人姓名" aria-label="审核人姓名"><div class="decisions"><button class="decision" data-value="accept">1 确认合格</button><button class="decision" data-value="rework">2 退回返工</button><button class="decision" data-value="reject">3 拒收</button><button class="decision" data-value="unsure">4 需仲裁</button></div><div class="defects" id="defects"></div><textarea class="note" id="note" placeholder="写清帧号、问题方向和返工要求" aria-label="复检备注"></textarea><p class="policy">系统不合格时，人工确认合格会进入误报仲裁，不会直接覆盖门禁。供应商返工必须提交新 revision。</p></section><section class="section"><div class="section-head"><h2>审核记录</h2><span id="history-count"></span></div><div class="history" id="history"></div></section></aside></main></div>
<dialog class="shortcut-dialog" id="shortcut-dialog"><header><h2>键盘快捷键</h2><button id="close-shortcuts">关闭</button></header><div class="keys"><div class="key"><kbd>J / K</kbd><span>下一条 / 上一条</span></div><div class="key"><kbd>1 2 3 4</kbd><span>记录人工结论</span></div><div class="key"><kbd>[ / ]</kbd><span>上一帧 / 下一帧</span></div><div class="key"><kbd>O / M</kbd><span>原始帧 / MANO 拟合</span></div><div class="key"><kbd>V</kbd><span>原始视频</span></div><div class="key"><kbd>Space</kbd><span>播放 / 暂停</span></div><div class="key"><kbd>?</kbd><span>打开本说明</span></div></div></dialog>
<script>
const records=__PAYLOAD__;const dataset=__DATASET__;const storageKey="egoqc-workbench:"+dataset;let index=0;let filter="all";let mediaMode="sheet";let frameIndex=0;let livePolling=true;let reviews={};
try{reviews=JSON.parse(localStorage.getItem(storageKey)||"{}")}catch(error){reviews={}}
const $=id=>document.getElementById(id);const issueLabels={position_jitter:"位置抖动",wrist_rotation_jitter:"腕部旋转抖动",joint_rotation_jitter:"关节旋转抖动",temporal_spike:"孤立跳点",mask_flicker:"检测闪烁",world_camera_position_mismatch:"相机位置不一致",world_camera_rotation_mismatch:"相机旋转不一致",video_blur_candidate:"视频模糊",video_exposure_candidate:"曝光异常"};
const defectOptions=[["jitter","抖动"],["offset","几何错位"],["penetration","穿模"],["occlusion","遮挡"],["handedness","左右手错误"],["sync","视频同步"],["video","视频质量"],["other","其他"]];
const decisionLabels={accept:"合格",rework:"返工",reject:"拒收",unsure:"仲裁"};
$("defects").innerHTML=defectOptions.map(([value,label])=>`<label><input type="checkbox" value="${value}">${label}</label>`).join("");
function save(){localStorage.setItem(storageKey,JSON.stringify(reviews))}function current(){return records[index]}function reviewFor(r=current()){return reviews[r?.episode_index]||{}}
function effectiveDecision(r){const human=reviewFor(r).decision;return human==="accept"&&r.system_decision!=="accept"?"escalated":human}
function risk(r){const weight={reject:5,rework:4,review:3,unscored:2,accept:1}[r.system_decision]||2;return weight*100+(r.issues||[]).length}
function visibleRecords(){const q=$("search").value.trim().toLowerCase();const sort=$("sort").value;const rows=records.filter(r=>{const review=reviewFor(r),effective=effectiveDecision(r);const text=[r.episode_index,r.source_video,r.system_decision,...(r.issues||[]).map(i=>i.code+" "+i.message)].join(" ").toLowerCase();const filterOk=filter==="all"||(filter==="pending"&&!review.decision)||(filter==="reviewed"&&review.decision)||(filter==="rework"&&r.system_decision==="rework")||(filter==="escalated"&&effective==="escalated");return filterOk&&(!q||text.includes(q))});return rows.sort((a,b)=>sort==="episode"?a.episode_index-b.episode_index:sort==="pending"?Number(Boolean(reviewFor(a).decision))-Number(Boolean(reviewFor(b).decision))||risk(b)-risk(a):risk(b)-risk(a))}
function renderQueue(){const visible=visibleRecords();$("queue").innerHTML=visible.length?visible.map(r=>{const position=records.indexOf(r),human=effectiveDecision(r);return `<button class="queue-item ${position===index?"active":""}" data-index="${position}"><b>EP ${String(r.episode_index).padStart(6,"0")}</b><span class="status ${r.system_decision}">${r.system_decision.toUpperCase()}</span><small>${human?"人工 "+(decisionLabels[human]||"仲裁"):"待人工复检"} | ${(r.issues||[]).length} 个问题</small></button>`}).join(""):`<div class="empty-page">当前筛选没有任务</div>`;document.querySelectorAll(".queue-item").forEach(button=>button.onclick=()=>{index=Number(button.dataset.index);frameIndex=0;render()})}
function anomalyFrames(r){return new Set((r.issues||[]).flatMap(issue=>issue.frames||issue.frame_indices||[]).map(Number))}
function metricRows(r){const keys=[["left_position_jitter_p99_mm","左手位置 p99","mm"],["right_position_jitter_p99_mm","右手位置 p99","mm"],["left_wrist_rotation_jitter_p99_deg","左腕旋转 p99","deg"],["right_wrist_rotation_jitter_p99_deg","右腕旋转 p99","deg"],["left_joint_rotation_jitter_p99_deg","左关节 p99","deg"],["right_joint_rotation_jitter_p99_deg","右关节 p99","deg"],["right_temporal_spike_count","右手跳点","帧"]];return keys.filter(([key])=>r.metrics?.[key]!=null).map(([key,label,unit])=>`<span>${label}</span><span>${Number(r.metrics[key]).toFixed(unit==="帧"?0:2)} ${unit}</span>`).join("")}
function renderRail(){const r=current(),frames=r.evidence_frames||[],anomalies=anomalyFrames(r);frameIndex=Math.max(0,Math.min(frameIndex,Math.max(0,frames.length-1)));$("frame-rail").innerHTML=frames.map((frame,i)=>`<button class="frame-thumb ${i===frameIndex?"active":""} ${anomalies.has(frame.frame_index)?"anomaly":""}" data-frame="${i}" title="frame ${frame.frame_index}${anomalies.has(frame.frame_index)?"，系统异常":""}"><img src="${frame.overlay_image||frame.image}" alt="frame ${frame.frame_index}" loading="lazy"><span>F${frame.frame_index}${frame.mano_status==="failed"?" MANO失败":""}</span></button>`).join("");document.querySelectorAll(".frame-thumb").forEach(button=>button.onclick=()=>{frameIndex=Number(button.dataset.frame);if(mediaMode==="sheet"||mediaMode==="source"||mediaMode==="annotated")mediaMode="overlay";setMedia();renderRail()});$("frame-position").textContent=frames.length?`${frameIndex+1} / ${frames.length}`:"0 / 0"}
function setMedia(){const r=current(),frame=(r.evidence_frames||[])[frameIndex],image=$("image"),video=$("video"),empty=$("media-empty");image.hidden=true;video.hidden=true;empty.hidden=true;video.pause();let source=null;if(mediaMode==="sheet")source=r.contact_sheet;else if(mediaMode==="frame")source=frame?.image;else if(mediaMode==="overlay")source=frame?.overlay_image||frame?.image;if(source){image.src=source;image.hidden=false}else if(mediaMode==="source"||mediaMode==="annotated"){const fileUri=mediaMode==="source"?r.video_uri:r.annotated_video_uri;const uri=location.protocol==="file:"?fileUri:(fileUri?`/api/media/${mediaMode}/${r.episode_index}`:null);if(uri){if(video.dataset.uri!==uri){video.src=uri;video.dataset.uri=uri;video.onloadedmetadata=()=>{if(mediaMode==="source")video.currentTime=r.start_time}}video.hidden=false}else{empty.textContent="当前 episode 没有该类视频";empty.hidden=false}}else{empty.textContent="当前抽样帧没有该类证据";empty.hidden=false}document.querySelectorAll("[data-media]").forEach(button=>button.classList.toggle("active",button.dataset.media===mediaMode));$("annotated-tab").disabled=!r.annotated_video_uri;renderRail()}
function issueKey(issue,i){return issue.code+":"+(issue.frames||issue.frame_indices||[]).join(",")+":"+i}
function renderIssues(r,review){const verdicts=review.issue_verdicts||{};$("issues").innerHTML=(r.issues||[]).length?r.issues.map((issue,i)=>{const key=issueKey(issue,i),verdict=verdicts[key];return `<div class="issue"><b>${issueLabels[issue.code]||issue.code}</b><span class="status ${issue.severity||"review"}">${issue.severity||"review"}</span><p>${issue.message}</p><div class="issue-actions" data-issue="${key}"><button data-verdict="confirmed" class="${verdict==="confirmed"?"selected":""}">确认问题</button><button data-verdict="false_positive" class="${verdict==="false_positive"?"selected":""}">误报</button><button data-verdict="unclear" class="${verdict==="unclear"?"selected":""}">不确定</button></div></div>`}).join(""):'<div class="empty">没有结构化失败原因</div>';document.querySelectorAll(".issue-actions button").forEach(button=>button.onclick=()=>{const key=button.parentElement.dataset.issue;updateReview({issue_verdicts:{...(reviewFor().issue_verdicts||{}),[key]:button.dataset.verdict}},"issue_verdict")})}
function renderHistory(review){const rows=(review.history||[]).slice().reverse();$("history-count").textContent=`${rows.length} 条`;$("history").innerHTML=rows.length?rows.slice(0,8).map(row=>`<div class="history-row"><time>${new Date(row.at).toLocaleString()}</time><span>${row.action}${row.decision?"，"+(decisionLabels[row.decision]||row.decision):""}${row.reviewer?"，"+row.reviewer:""}</span></div>`).join(""):'<div class="empty">本机暂无审核记录</div>'}
function render(){const r=current();if(!r){$("queue").innerHTML='<div class="empty-page">没有复检任务</div>';return}renderQueue();const review=reviewFor(r);$("system-decision").textContent=r.system_decision==="accept"?"原始数据通过":r.system_decision==="rework"?"供应商返工":r.system_decision==="reject"?"原始数据拒收":"需要人工判断";$("gate").className="gate "+r.system_decision;$("gate-copy").textContent=`Tier ${r.tier}，motion_pass=${r.motion_pass==null?"未计算":r.motion_pass}。人工结论不覆盖源门禁。`;$("provisional").textContent=r.provisional?"计算中":"结果已固化";renderIssues(r,review);$("metrics").innerHTML=metricRows(r)||'<span class="empty">没有可显示指标</span>';$("frame-range").textContent=`${Number(r.start_time).toFixed(2)}-${Number(r.stop_time).toFixed(2)} s | 抽样 ${(r.evidence_frames||[]).length} 帧`;$("source-path").textContent=r.source_video;$("reviewer").value=review.reviewer||localStorage.getItem("egoqc-reviewer")||"";$("note").value=review.note||"";document.querySelectorAll(".decision").forEach(button=>button.classList.toggle("selected",button.dataset.value===review.decision));document.querySelectorAll("#defects input").forEach(input=>input.checked=(review.defects||[]).includes(input.value));$("review-state").textContent=review.decision?`已记录 ${decisionLabels[review.decision]}`:"尚未复检";renderHistory(review);setMedia();const done=records.filter(r=>reviewFor(r).decision).length;$("progress").textContent=`${done}/${records.length} 已复检`}
function updateReview(patch,action="edit"){const r=current(),previous=reviewFor(r),now=new Date().toISOString(),reviewer=$("reviewer").value.trim(),history=[...(previous.history||[])];const decision=patch.decision??previous.decision;if(action!=="edit"||patch.decision!==undefined)history.push({at:now,action,decision,reviewer});reviews[r.episode_index]={...previous,...patch,reviewer,note:$("note").value,defects:[...document.querySelectorAll("#defects input:checked")].map(input=>input.value),reviewed_at:now,history};save();render()}
function decide(value){updateReview({decision:value},"decision")}function move(delta){index=Math.max(0,Math.min(records.length-1,index+delta));frameIndex=0;render()}function moveFrame(delta){const length=(current().evidence_frames||[]).length;if(!length)return;frameIndex=(frameIndex+delta+length)%length;if(mediaMode==="sheet")mediaMode="overlay";setMedia()}
document.querySelectorAll(".decision").forEach(button=>button.onclick=()=>decide(button.dataset.value));document.querySelectorAll("[data-media]").forEach(button=>button.onclick=()=>{mediaMode=button.dataset.media;setMedia()});document.querySelectorAll("[data-filter]").forEach(button=>button.onclick=()=>{filter=button.dataset.filter;document.querySelectorAll("[data-filter]").forEach(item=>item.classList.toggle("active",item===button));renderQueue()});$("search").oninput=renderQueue;$("sort").onchange=renderQueue;$("note").onchange=()=>updateReview({},"note");$("reviewer").onchange=()=>{localStorage.setItem("egoqc-reviewer",$("reviewer").value.trim());updateReview({},"reviewer")};$("defects").onchange=()=>updateReview({},"defects");$("prev-frame").onclick=()=>moveFrame(-1);$("next-frame").onclick=()=>moveFrame(1);
$("video").ontimeupdate=()=>{const r=current();if(mediaMode==="source"&&$("video").currentTime>=r.stop_time)$("video").pause()};
const dialog=$("shortcut-dialog");$("shortcuts").onclick=()=>dialog.showModal();$("close-shortcuts").onclick=()=>dialog.close();document.onkeydown=event=>{if(["INPUT","TEXTAREA","SELECT"].includes(event.target.tagName))return;const key=event.key.toLowerCase();if(key==="k"||event.key==="ArrowLeft")move(-1);if(key==="j"||event.key==="ArrowRight")move(1);if(event.key==="[")moveFrame(-1);if(event.key==="]")moveFrame(1);if("1234".includes(event.key))decide(["accept","rework","reject","unsure"][Number(event.key)-1]);if(key==="o"){mediaMode="frame";setMedia()}if(key==="m"){mediaMode="overlay";setMedia()}if(key==="v"){mediaMode="source";setMedia()}if(event.key==="?")dialog.showModal();if(event.key===" "){event.preventDefault();if(mediaMode!=="source"&&mediaMode!=="annotated"){mediaMode="source";setMedia()}else{$("video").paused?$("video").play():$("video").pause()}}};
$("export").onclick=()=>{const reviewer=$("reviewer").value.trim();const lines=records.filter(r=>reviewFor(r).decision).map(r=>{const human=reviewFor(r),overrideRequested=human.decision==="accept"&&r.system_decision!=="accept";return JSON.stringify({dataset_root:dataset,episode_index:r.episode_index,source_video:r.source_video,start_time:r.start_time,stop_time:r.stop_time,system_decision:r.system_decision,human_decision:human.decision,effective_decision:overrideRequested?"escalate":human.decision,override_requested:overrideRequested,reviewer:human.reviewer||reviewer,defects:human.defects||[],issue_verdicts:human.issue_verdicts||{},note:human.note||"",reviewed_at:human.reviewed_at,history:human.history||[]})});const blob=new Blob([lines.join("\n")+(lines.length?"\n":"")],{type:"application/x-ndjson"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="human-reviews.jsonl";link.click();URL.revokeObjectURL(link.href)};
$("import").onclick=()=>$("file").click();$("file").onchange=async event=>{try{const text=await event.target.files[0].text();for(const line of text.split(/\r?\n/)){if(!line.trim())continue;const row=JSON.parse(line);reviews[row.episode_index]={decision:row.human_decision||row.decision,note:row.note||"",defects:row.defects||[],issue_verdicts:row.issue_verdicts||{},reviewer:row.reviewer||"",reviewed_at:row.reviewed_at,history:row.history||[]}}save();render()}catch(error){alert("导入失败: "+error.message)}};
async function pollLive(){if(!livePolling)return;try{const response=await fetch("/api/live",{cache:"no-store"});if(!response.ok){if(response.status===404){livePolling=false;$("live-status").textContent="离线数据"}return}const data=await response.json(),status=data.registry_run||data.status||{},fraction=Number(status.progress_fraction??status.fraction??0),state=status.status||"running",eta=status.eta_seconds??status.eta_s;$("live-status").textContent=`${state.toUpperCase()} ${(fraction*100).toFixed(1)}%${eta!=null?" | ETA "+Math.ceil(eta)+"s":""}`;let changed=false,currentChanged=false;for(const incoming of data.episodes||[]){const acceptance=incoming.acceptance||{},existing=records.find(record=>record.episode_index===incoming.episode_index),update={system_decision:acceptance.decision||incoming.system_decision||"unscored",motion_pass:acceptance.motion_pass??incoming.motion_pass,tier:incoming.tier||"unknown",issues:incoming.issues||[],metrics:incoming.metrics||{},provisional:Boolean(incoming.provisional)};if(existing){const before=JSON.stringify([existing.system_decision,existing.motion_pass,existing.tier,existing.issues,existing.metrics,existing.provisional]),after=JSON.stringify([update.system_decision,update.motion_pass,update.tier,update.issues,update.metrics,update.provisional]);if(before!==after){Object.assign(existing,update);changed=true;currentChanged=current()?.episode_index===existing.episode_index}}else{records.push({episode_index:incoming.episode_index,contact_sheet:"",sampled_frames:incoming.sample_frames||[],evidence_frames:[],source_video:"证据生成中",video_uri:null,annotated_video_uri:null,start_time:0,stop_time:0,mano_rendered:0,mano_failed:0,...update});changed=true}}if(changed){records.sort((a,b)=>a.episode_index-b.episode_index);renderQueue();const editing=["INPUT","TEXTAREA","SELECT"].includes(document.activeElement?.tagName);if(currentChanged&&!editing)render()}}catch(error){livePolling=false;$("live-status").textContent="离线数据"}}
render();pollLive();setInterval(pollLive,2000);
</script></body></html>'''
